### ISSUE TITLE
Avira recognises .exe as TR/Dropper.Gen2 virus

### ISSUE THREAD

**Issue by dandantheflyingman** [ninthwalker/saverr#1]
https://www.avira.com/en/support-threats-summary-product?tid=4537&threat=TR%252FDropper.Gen2

**Comment by pc-ballen** [comment]
This prob can't be fixed. The powershell script was just converted with the PS2EXE tool. So it's not signed, and maybe it flags it like that since it's doing web calls to the plex.tv site and servers? Not sure.
https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5

I mention in the readme that you can make your own .exe from the script if wanting, or not use the .exe and just use the straight Powershell script. Thanks for letting me know that the antivirus flagged it though.

**Comment by ninthwalker** [comment]
This prob can't be fixed. The powershell script was just converted with the PS2EXE tool. So it's not signed, and maybe it flags it like that since it's doing web calls to the plex.tv site and servers? Not sure.
https://gallery.technet.microsoft.com/scriptcenter/PS2EXE-GUI-Convert-e7cb69d5

I mention in the readme that you can make your own .exe from the script if wanting, or not use the .exe and just use the straight Powershell script. Thanks for letting me know that the antivirus flagged it though.
