### ISSUE TITLE
Feature-Request: Download-link copy to clipboard

### ISSUE THREAD

**Issue by XtremeCoder007** [ninthwalker/saverr#12]
Hi,

Is it possible to add a button to export all Download-urls to clipboard so this can be downloaded by a download manager or "download station" (synology) ?

Thanks in advance,

XtremeCoder

**Comment by XtremeCoder007** [comment]
i've found a way to do it, dirty but it works
below line 1458 - for movies
` $dlUrl | Out-File -FilePath .\movie-url.txt -append`
below line 1486 - for episodes
`$allep.source | Out-File -FilePath .\eps-url.txt -append`

might need to create files first

**Comment by amaurynieto** [comment]
I can see the path perfectly. Is there a way for me to append these without actually having to click download on each?

Example, I have the Star Wars movies. 
![image](https://user-images.githubusercontent.com/32950225/80551656-d0831d80-8989-11ea-867d-e4a1b8237bf7.png)

Instead of me having to click Download on each (which populates the download link for each), I'd like to just have the selection automatically show and append on movie-url.

`http://1*********.2*0:10154/library/parts/46939/1556102437/file.mkv?download=1&X-Plex-Token=Nt6MurE9xkniSjF2234a
http://1*********.2*0:10154/library/parts/87988/1578403990/file.mp4?download=1&X-Plex-Token=Nt6MurE9xkniSjF2234a
`

**Comment by ninthwalker** [comment]
I probably wont be adding this in. As you mentioned, you can get the url's with the export code you did. The way the app is designed is a bit different in its functionality than a mass url downloader.
