### ISSUE TITLE
Doesn't work when secure connections are set to required

### ISSUE THREAD

**Issue by Pyrogeen** [ninthwalker/saverr#2]
Hello,
when PMS is set to require secure connections saverr throws "Error! Check settings/token/server status?".
It seems to only work over http, not https, writing https only domain name in the config doesn't help.
Steps to reproduce:
PMS => Settings => Network => Secure connections => Required

**Comment by pc-ballen** [comment]
Thanks for the bug report. I'll look into testing it and see about getting it to work for required-only servers

**Comment by derisor** [comment]
I'm getting this same error.  Any known workaround for this?

**Comment by ninthwalker** [comment]
This has been fixed in the latest version. (1.1.0)
For servers that have the Secure Connections set to 'required', there is now an option in the settings menu you can check called 'SSL Required'. Please select that and restart the app and try again.

There had to be some workarounds put in the code to get this to work with how IP's don't match the CN of most certificates. I tested my method a bit, but do not have many plex servers shared with me that have that option set. So if you still have issues, open another ticket and let me know. Thanks!
